### ISSUE TITLE
Revisit custom pseudo state parameter type "Tag"

### ISSUE THREAD

**Issue by barak007** [wix/stylable#1552]
After moving from data-attribute based states to class based states the `tag` state parameter feels very similar to the `string` one.

We need to revisit what was the feature idea and re-implement it or remove it.

**Comment by idoros** [comment]
The current status is that `tag` and `string` are the same. Before when states were set as attributes, a tag state selector like `Item:tags(shirt)` would be transformed to `item__root[tags~="shirt"]` to match one of possible values that the view has set on the item element using spaces: `<item tags="shirt pants">`. the special case for the transformed attribute selector (`~=` splits the value by spaces and match each splitted value) was not needed as class selector already assumes class names are delimited by spaces. 

But the ability to set multiple values on a state was not reimplemented in the new runtime `st function`. Before you would pass a string with space delimited tags, but there is no equivalence now (spaces are transformed to `_`). potentially the state function could accept an array of string values for a state and spread the inner  transformed classes.

Although I don't have good real life cases for such states. The issue is that tags are usually dynamic and changing while css is static and every example feels weird.

**Comment by idoros** [comment]
removed in #2485
