### ISSUE TITLE
`-st-global` does not export correctly 

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#1972]
### Actual Behavior

When using `-st-global`, the declaration does not transform as expected, but it does transform in the javascript exports.

[Playground link](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%28*%21%27.y%2520%280%2520%2520%2520%2520-st-global%253A%2520%255C%27.x%255C%27%253B0%29000%27%29%7Eselected%21*%27%29*%27%252Findex.st.css0%255Cn%25010*_)

### Expected Behavior

Transform in both CSS and javascript.

### Version

4.5.0

**Comment by idoros** [comment]
The behavior this issue reports is opposite of the current observed behavior - currently the transformation works as expected, while the JS exports provide the namespaced class name instead of the `-st-global` selector. see [reproduction](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%280%21%27.y%2520%28%2520%252F*%2520replaced%2520with%2520%25602%2560%2520selector%2520value%25203%2520%2520%2520%25202%253A%2520%255C%27.x%255C%27%253B1%2911%252F****%2520js%2520export%2520expected%2520%2560y%253Ax%2560%2520***3%27%29%7Eselected%210%27%290%27%252Findex.st.css1%255Cn2-st-global3*%252F1%25013210_)

Fixing this should resolve the value exported for a simple class, but we need to handle problematic cases:
- composed classes: `.a.b` -> `a b`
- complex selector: `.a .b` ->
    - option 1: report `complex selectors is not supported in -st-global` and maybe export empty or `.b`
    - option 2: export `.b` and create a custom selector for `::part` -> `& .a .b`
- native states: `.a:hover` ->
    - option 1: report `pseudo-class in not supported in -st-global` and maybe export empty or `.a`
    - option 2: export `.a` and create a custom selector for `::part` -> `& .a:hover`
