### ISSUE TITLE
stylesheet function behavior 

### ISSUE THREAD

**Issue by barak007** [wix/stylable#201]
make stylesheet function only add root className when used with props

**Comment by adriantoine** [comment]
Hi @barak007,

I have been looking at the code and I have a few questions.

- Looking at [these tests](https://github.com/wix/stylable/blob/master/tests/runtime.spec.ts#L49-L51) it seems that they are actually expect the root className to always be there, so I guess those tests have to be modified.
- Also what is the differen between the className passed in the first parameter and the one passed in the props?
For example:
```js
runtime('item', {}, {className: 'item-from-props'})
```
It seems that they are pretty much the same thing while I would expect the first parameter `'item'` to be the class name from the stylesheet (so `namespace--item` if `.item` is in the stylesheet) and if users want to add a fully custom `className` they can use the props.

So:
```js
runtime('item', {}, {className: 'item-from-props'})
```
should return `namespace--item item-from-props` instead of `item item-from-props`.

And
```js
runtime('item') // no props provided
```
should just return `namespace--item`, the class name from the stylesheet, even if props are not provided.

What do you think about that?

I would like to make a PR if you agree.

**Comment by adriantoine** [comment]
Oh hold on, there is a PR already, ignore the last line then 😁

**Comment by barak007** [comment]
Mapping className string automatically is slower then simply passing it through, when you already have reference to the mapped class. 

Perhaps we should discuss adding alternative API that automatically maps the className.

Something of this sort:
```js
(s: string=>s.split(' ').map((c)=>(style[c] || c)))
```

We've updated the behavior and the documentation to clarify this:
https://github.com/wix/stylable/blob/21d4ea3c107967bd6582c1ca5896bba4f2db3f9a/site/docs/getting-started/react-integration.md
Please check it out and let me know if the documentation is clearer now.

**Comment by adriantoine** [comment]
Yeah the new documentation is a lot more clear.

My point is that I find it weird that this:

```js
import stylesheet from './style.st.css';

stylesheet('my-class');
```

returns just `my-class` even if `.my-class` is defined in the stylesheet, that's just not what I would expect. 

To get my class with the states, I'd have to write:

```js
import stylesheet from './style.st.css';

stylesheet(stylesheet['my-class'], {visible: true});
```

which feels very verbose to write `stylesheet` twice.

If I want a global class name to be added I can do:
```js
import cx from 'classnames';

<div className={cx('global-class', stylesheet('my-class'))}>
...
```

Especially that in 99% of cases you don't want to use global class names with stylable, you want the classes from your stylesheet.

**Comment by idoros** [comment]
I think you are 100% correct. And I modified the docs in the PR accordingly, separating a general [runtime guide](https://github.com/wix/stylable/blob/6f422b1e23d1f003ad9173d9a94e59efae6389af/site/docs/guides/runtime.md) and rewriting the [manual react integration](https://github.com/wix/stylable/blob/6f422b1e23d1f003ad9173d9a94e59efae6389af/site/docs/getting-started/react-integration.md).

I added links to the new docs in the PR and we will modify the behavior accordingly. Thanks for the input @adriantoine!

**Comment by adriantoine** [comment]
@idoros no problem, I was just sharing my opinion! I'm glad you updated it! 😄
