### ISSUE TITLE
What is CSS API?

### ISSUE THREAD

**Issue by mrac** [wix/stylable#221]
Let's consider developing a component library with Stylable and using semantic versioning (with only major upgrades allowed to break API). The question arises: What is API regarding CSS?

What constitutes CSS API for a component in Stylable? I guess `states` (pseudo-classes) and `elements` (pseudo-elements). But what about CSS properties? What about the way how component interacts with its surroundings (position/display etc.)?

I ask this questions because I'm excited Stylable has a good chance to solve most of CSS problems :) This is one of them.

**Comment by idoros** [comment]
That's a really great queastion! and we still need to figure it out :) 

The good thing is, that while these concerns are relevent to almost anyone with CSS dependencies, we have an opportunity to leverage more knowlage of project style hierarchy in order to figure out when dependencies are broken.

As you said there are 2 noticeable types of definitions in Stylable:

## Pseudo Elements & Pseudo States

Well suited for classic interface as we know it. Pseudo interfaces removal/override are probably major changes while modification might be a little more flexible thanks to features related to `Definitly Styled` (features which allow the definition of style API for components that are not build with stylable in mind).

## Properties

The cascade is great, but it means everything is potentially inherited by nested interleaved light & shadow DOM. Component might add `color:red` and break an external usage that was counting on an ancestor color to go through and affect a nested element. As far as I know, this is an issue with Web Components as well.  

We are talking about declaration interfaces that allows a component stylesheet to restrict overrides or even require overrides (essentially a blacklist/whitelist for rule declarations). This should give some flexibility when refactoring / fixing code.

And again, because this is basically CSS, we can leverage stuff like [all:initial](https://developer.mozilla.org/en-US/docs/Web/CSS/all) and any other [best practices](https://stylable.io/docs/guides/stylable-component-best-practices) for components - which I think should have a section warning for setting certain declarations, like display and position for the root element (except for edge cases).

-----

So we are not sure, but this is definitely on our mind and we are happy to have this conversation :)

**Comment by mrac** [comment]
This is really interesting topic. As you look closer into CSS to see how to make it as modular and scalable as JavaScript, you figure out interesting things..

### Isolation
@idoros good point about CSS inheritance! Before even speaking about CSS API I think we need to make sure component CSS is really isolated and no implicit influence takes place. As you pointed out many of the CSS properties are by default inherited (mostly those related to text like `color`, `font`, `letter-spacing` etc.):
https://www.w3.org/TR/CSS21/propidx.html
and that makes a component affected implicitly by its parent. Setting `all:initial` seems to be the trick! Unfortunately it's not supported by Edge browser yet:
https://caniuse.com/#feat=css-all
Another thing to understand is it resets properties to their initial values, regardless the element. So setting it on `div` would reset `display` to `inline`. That is rarely useful as component's default, so it would be good to always pair it with `display:block` for component's root.

Another good practice would be to always set `position` of the component's root element to something other than `static`. Otherwise any "absolutely positioned" elements inside a component could be potentially positioned relatively to the context somewhere outside the component itself. Setting `position: relative` by default on the root element simply makes sure the positioning context is never outside, even if we forget to set it. It also works for `z-index`.

### API
I took a closer look into CSS properties and figured out that some of them are really meant not to be set by the component itself, but by its consumer. For example all those properties responsible for setting its position. For a component, properties like `position`, `flex`, `flex-grow`, `flex-shrink`, `flex-basis`, `order`, `align-self`, `left`, `right`, `top`, `bottom`, `z-index` on the root element are meant to be set by its parent, to position the component. Therefore they should be somehow made `public` and safe to set in the parent component.

I think `width` and `height` should be also public/safe for the parent. Any internal limitations to component sizing should be rather limited by `min-width`,`min-height`,`max-width`,`max-height`.

**Comment by tomrav** [comment]
Closing this issue, in favor of #293
