### ISSUE TITLE
Bad transpile of negative variable values with '-value(variable)'

### ISSUE THREAD

**Issue by tomerlichtash** [wix/stylable#249]
The following will **not** result with a negative borderSize:
```
  left: -value(borderSize);
```
It should result with:```left: -1```.

**Comment by idoros** [comment]
This happens because when parsing the declaration value, we see `-value` as the function. we could search for available functions within the function name, but we need to consider how [custom CSS functions]() will work with this.

In the mean while, a possible workaround is to use `calc()` to mitigate the value: 
```css
* {
    left: calc(-1 * value(borderSize));
}
```

**Comment by tomrav** [comment]
Will not implement this feature as we feel it contradicts with native syntax. The CSS calc approach should work.
