### ISSUE TITLE
Var names "Best Practices"

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable#264]
issues raised in VSCode extension re: using CSS reserved values as var can cause weird behavior in the editor. for example, if you call some off-white color "white", then you'll have 2 color boxes next to the text, one for your value and one for white.

need to add a best practice explanation, hopefully with some screenshots from @tempit

**Comment by tempit** [comment]
Not just vars. States and classes as well. It's even worse there, because you get different parts of the same selector in different colors. 
In general, if we want to allow CSS reserved words as Stylable tokens, we need to completely re-write the syntax highlights or it will look bad. This means adding dynamic recognition of variables, etc. into single-line based RegEx syntaxes, which is somewhere between hard and impossible. 

So 3 not so good choices:
1. Disallow CSS reserved word use in Stylable (if you want a var called background, use _background or my-background, etc.)
2. Write completely new TextMate/Monarch files (very time-consuming, not necessarily possible to do everything we want, very low ROI IMO).
3. Allow users to use CSS words as names, at the expense of a bad tooling experience (current). 

I'm for the 1st option, naturally.

**Comment by tempit** [comment]
Another, more convoluted option, but ultimately maybe closer to what we want:
Issue low-severity diagnostics for reserved words as tokens, that will not fail build.
Have config option in stylable-intelligence, 'allowReservedWordsAsTokens' and I can hide or show diagnostics accordingly.

**Comment by tomrav** [comment]
Personally, so long as the effect is visual only, I'm in favor of issuing diagnostics and not blocking keywords.
