### ISSUE TITLE
Using with "portals"

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#281]
How to use Stylable with React portals?

Example:
```
render() {
  return (
    <div>
      {createPortal((
        <div class='tooltip'>
          {children}
        </div>
      ), document.body)}
    </div>
  );
```
In DOM `tooltip` is not inside root and styles will not be applied.
Also I can do this:
```
render(){
  return (
    <div>
      {createPortal((
        <Tooltip>
          {children}
        </Tooltip>
      ), document.body)}
    </div>
  );
```
but custom styles or theme styles will not be applied.

**Comment by idoros** [comment]
This problem is not directly a Stylable issue, but a general CSS problem.

Portals "break" complex selectors that target across the portal boundry.

Stylable currently makes this problem worse by "scoping" every selector with a `.root` class in order to prevent global selectors from "leaking" outside of the stylesheet bounderies. Essentially making every selector a complex selector. We are going to remove this automatic scoping soon, but currently you can do it yourself by passing `rootScope:false` to the `StylablePlugin` in the Webpack config:

```
{
    plugins: [
        new StylablePlugin({ rootScope: false })
    ]
}
```

The simple solution (with simple results) is to manually add the application root / theme to the root of a portal. We are playing with a [solution](https://github.com/wix/html-overlays) that manages portals/overlays and provides better support for CSS. 

I hope that as portals become more common, the spec will provide a native solution that will allow developers to hint relocated nested DOM. But that will probably take some time...

**Comment by dangreen** [comment]
@idoros 
with `rootScope: false`
```
Tooltip::tooltip {
	color: red;
}
```
transforms to
```
.Tooltip2039582536🦄root .Tooltip2039582536🦄tooltip {
	color: red;
}
```
I think will be better if this will transforms to
```
.Tooltip2039582536🦄tooltip {
	color: red;
}
```

**Comment by idoros** [comment]
Removing the root scoping means stopping the automatically added `.root` class to any selector in any stylesheet, e.g. `.classA` transforms into `.comp__root .comp__classA`.

Writing `Tooltip::tooltip` is a selector for the element Tooltip and then another pseudo-selector for an internal part of the Tootltip with the name tooltip. Removing the first part will style EVERY internal tooltip part in the application context.

If you want this behavior, you could import the internal `tooltip` class and use it directly:
```
:import {
    -st-from: "./tooltip.st.css";
    -st-named: tooltip; /* notice this is a named import */
}
.tooltip {} /* result: ".Tooltip__tooltip {}" */
```
I would suggest that if you want to style internal parts globally like this, that you would do this at the top level of your application.

**Comment by idoros** [comment]
We could give a selector util to target an internal part directly:
```css
:internal(Tooltip::tooltip) {}
:internal(Gallery::navBtn::label) {}
```

will transform to:

```css
.Tooltip__tooltip {}
.Label__root {}
```
