### ISSUE TITLE
cannot define pseudo states inside complex selectors

### ISSUE THREAD

**Issue by lbelinsk** [wix/stylable#360]
I am trying to put states on some element which is not the root element.

![image](https://user-images.githubusercontent.com/18248989/41842558-d4b3db70-7873-11e8-94e6-260e0821e319.png)

![image](https://user-images.githubusercontent.com/18248989/41842503-a64580ae-7873-11e8-8b8a-469c7b64b140.png)

Maybe I am doing something wrong, but this works for me only if I remove the ".root" it works:

![image](https://user-images.githubusercontent.com/18248989/41842602-f2927c64-7873-11e8-82f0-a7575b5b17e1.png)

This is not just a warning, I can't see my component at all when this error occurs.

**Comment by tomrav** [comment]
Is `.progressBar` a local class in this case? if it is, then it is already scoped to your stylesheet and does not require additional `.root` scoping.

**Comment by lbelinsk** [comment]
.progressBar is the grandchild of root, yes.
Isn't there a boolean we can config for root scoping?
What if it was false?

**Comment by tomrav** [comment]
Root scoping is already defaulted to false, that's why you're getting warnings like `unscoped native element ".someClass" will affect all elements of the same type in the document`.

In your case (I'm assuming, without seeing the entire stylesheet), your `.root` class was just not needed (increasing specificity for no reason). The warning about defining states in complex selectors (which, `.root .x` is) is also intended as that's what's currently supported by Stylable.

**Comment by lbelinsk** [comment]
Ok, thanks. From my side, you can close the issue.
