### ISSUE TITLE
Special characters in pseudo-class issues diagnostic

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#390]
Having a `File.st.css` file in the IDE (Vs code),
the default `css` linter will show an error in case a rule has only a mixin inside it.

The error being: `[css] at-rule or selector expected`

For example:
```
.root:appearance(T2.1) {
  -st-mixin: TextStyle(
    fontFamily value(fontRoman),
    fontSize 16px,
    lineHeight 24px,
    color value(placeholderText)
  );
}
```

I guess this rule can be disabled somehow.

Since there may be other rules as well that need to be disabled,
Or new rules which take into account Stylable syntax.

Could Stylable provide that for us?

**Comment by tomrav** [comment]
The diagnostics issued actually happens in the provided example due to the pseudo-class `:appearance(T2.1)` parameter including a `.` character. This causes the native CSS parser to break, which you can see a hint of by the text `T2.1` changing syntax highlighting color mid-string (using the `stylable-intelligence` extension).

Two possible solutions:
- wrap the state parameter in quotes, e.g. `:appearance("T2.1")`
- swap to a state parameter value that does not contain special characters, e.g. `:appearance(T2-1)`

In general I would be wary of using special characters with meaning in CSS for un-intended purposes.

Concerning native CSS rules, we do in fact filter a number of CSS linting validations that clash with Stylable, we can try and fine-tune this error as well, though it may be tricky.
