### ISSUE TITLE
stc --diagnostics throws name collision

### ISSUE THREAD

**Issue by mykas** [wix/stylable#423]
In `wix-ui-core` we have command npm generate-stylable-index which uses stc cli with parameter --diagnostics. This command throws naming collision error.

```bash
Error: Name Collision Error: /Users/mykolass/Documents/wix-ui/packages/wix-ui-core/dist/src/components/button-next/button-next.st.css and /Users/mykolass/Documents/wix-ui/packages/wix-ui-core/dist/src/themes/backoffice/button-next/button-next.st.css has the same filename
    at /Users/mykolass/Documents/wix-ui/packages/wix-ui-core/node_modules/stylable-integration/dist/src/build.js:21:23
    at Array.forEach (<anonymous>)
    at Object.build (/Users/mykolass/Documents/wix-ui/packages/wix-ui-core/node_modules/stylable-integration/dist/src/build.js:16:18)
    at Object.<anonymous> (/Users/mykolass/Documents/wix-ui/packages/wix-ui-core/node_modules/stylable-integration/dist/src/cli.js:37:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

Link to failing PR: https://github.com/wix/wix-ui/pull/731

Project structure:
- src
    - components
        - button-next
            - button-next.tsx
            - button-next.st.css
            - button-next.spec.ts
            - button-next.driver.ts
            - button-next.meta.ts
    - themes
        - backoffice
            - button-next
                - button-next.st.css

Is this by design not to let users create same file name in the same project?

**Comment by AviVahl** [comment]
Background for the issue:
`stc` currently auto-generates an `index.st.css` file exporting all `.st.css` files found in a library.
It does that in order for library consumers to be able to import stylesheets from a single entry point for the entire library.
For each `.st.css` file, it creates an exported symbol based on the file base name ("button-next.st.css", in this case). If two files have the same base name, the above error is thrown.

In order to resolve this, `@stylable/cli` could perhaps allow you to specify `"exclude"` or expose the blacklist option. PRs are welcome.

**Comment by mykas** [comment]
In the newest stc version we have naming collision happening only as warning in build. This is URGENT - we can't be sure if our builds are ok, because we get only warning but index.st.css is not generated. It took us couple of hours just to fix this in `wix-ui-core`.

**Comment by tomrav** [comment]
I've managed to reproduce the unhandled rejected promise and will proceed to fix it in the upcoming version so that it is managed properly, and quits the process with an error code.

Regardless of that, the latest release of the `@stylable/cli` was not supposed to automatically solve this issue (we can't, without making opinionated decisions for our users), instead, it exposed the ability for you to provide another parameter (`--customGenerator`) to the CLI pointing to a file containing a custom generator to be used during build.

Based on the received `filePath` argument, you could issue names that do not collide yourself, deciding on the correct strategy for your project.

You can see the default generator used by stylable [here](https://github.com/wix/stylable/blob/master/packages/cli/src/default-generator.ts)
You can find a test and a custom generator [here](https://github.com/wix/stylable/blob/master/packages/cli/test/generate-index.spec.ts#L79) and [here](https://github.com/wix/stylable/blob/master/packages/cli/test/fixtures/test-generator.ts).

Can you explain a bit further about what you're trying to do? Are all of these stylesheets going to end up together in the same bundle, or is there another separate process going on afterward to split them?

**Comment by tomrav** [comment]
After talking with @shlomitc another possible solution comes to mind.

Instead of having a single command build all of the `*.st.css` files in the project, split your `stc` command to two separate commands, generating two index files, one for `components` and one for `backoffice-theme`.
