### ISSUE TITLE
Styles in SSR are applied after the markup has loaded

### ISSUE THREAD

**Issue by lbelinsk** [wix/stylable#437]
Today the way yoshi works with stylable results with the styles are inline in the head tag.
In ssr this is problematic since we see the rendered page (which was rendered on the server side) and only after a few seconds the runtime generates the styles.

This is an example of how it looks like:
https://media.giphy.com/media/9rnH9mlx86BcyiPUfy/giphy.gif

**Comment by lbelinsk** [comment]
A possible solution is to load the css externally into a separate bundle, or into the css bundle yoshi creats..

**Comment by idoros** [comment]
Just to clarify, the case you describe is of a build process that takes `*.st.css` files and transforms each one of them into javascript modules that inject the CSS content at runtime. Then when the server serves the rendered HTML, the CSS is injected only after the javascript code loads. causing a restyle. This mode is useful for applications - not SSR sites.

I think that for a server-rendered application/site it would be better to transpile the `*.st.css` files into a `bundle.css` that would be served as part of the HTML response. For this to work we need:
 * persistent namespacing, so build and serve may be independent. that will work once #435 is merged and published (should be published soon). 
 * I think we should change the way we publish component projects so that we publish both `.st.css` & `.st.css.js` files with a pre calculated namespace.

**Comment by tomrav** [comment]
#435 has been merged and will be released soon.
